-- ==========================================================
-- GUILDS COMERCIAL — SEED DATA (v2 multi-tenant)
-- Cria org "Guilds" + membros + popula 45 leads (3 demo + 42 reais)
-- Requer: profiles já populada (pós criação dos 4 users no Auth).
-- ==========================================================

-- ==========================================================
-- Passo 1: cria a organização "Guilds", membros e home_org
--          + liga temporariamente o default organizacao_id
-- ==========================================================
do $$
declare
  uid_org      uuid;
  uid_gustavo  uuid := (select id from public.profiles where email = 'gustavog.macedo16@gmail.com' limit 1);
  uid_comerc   uuid := (select id from public.profiles where email = 'comercial@guilds.com.br'     limit 1);
  uid_sdr1     uuid := (select id from public.profiles where email = 'sdr1@guilds.com.br'          limit 1);
  uid_sdr2     uuid := (select id from public.profiles where email = 'sdr2@guilds.com.br'          limit 1);
begin
  if uid_gustavo is null then
    raise exception
      'profiles ainda não populada — crie os 4 usuários e rode o INSERT de profiles antes do seed.';
  end if;

  insert into public.organizacoes (nome, slug, owner_id)
  values ('Guilds', 'guilds', uid_gustavo)
  returning id into uid_org;

  insert into public.organizacao_config (organizacao_id)
  values (uid_org);

  insert into public.membros_organizacao (organizacao_id, profile_id, role) values
    (uid_org, uid_gustavo, 'gestor'),
    (uid_org, uid_comerc,  'comercial'),
    (uid_org, uid_sdr1,    'sdr'),
    (uid_org, uid_sdr2,    'sdr')
  on conflict (organizacao_id, profile_id) do nothing;

  update public.profiles
     set home_organizacao_id = uid_org
   where id in (uid_gustavo, uid_comerc, uid_sdr1, uid_sdr2);

  -- default temporário para os inserts subsequentes (removido no final)
  execute format('alter table public.leads        alter column organizacao_id set default %L', uid_org);
  execute format('alter table public.raio_x       alter column organizacao_id set default %L', uid_org);
  execute format('alter table public.cadencia     alter column organizacao_id set default %L', uid_org);
  execute format('alter table public.newsletter   alter column organizacao_id set default %L', uid_org);
  execute format('alter table public.ligacoes     alter column organizacao_id set default %L', uid_org);
  execute format('alter table public.meta_semanal alter column organizacao_id set default %L', uid_org);
  execute format('alter table public.meta_mensal  alter column organizacao_id set default %L', uid_org);
  execute format('alter table public.lead_evento  alter column organizacao_id set default %L', uid_org);
end $$;

-- ==========================================================
-- Passo 2: inserts de dados (usam o DEFAULT para organizacao_id)
-- ==========================================================
do $$
declare
  uid_gustavo  uuid := (select id from public.profiles where email = 'gustavog.macedo16@gmail.com' limit 1);
  uid_comerc   uuid := (select id from public.profiles where email = 'comercial@guilds.com.br'     limit 1);
  uid_sdr1     uuid := (select id from public.profiles where email = 'sdr1@guilds.com.br'          limit 1);
  uid_sdr2     uuid := (select id from public.profiles where email = 'sdr2@guilds.com.br'          limit 1);
begin

-- ----- 3 leads-exemplo (is_demo = true) -----
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, email, whatsapp, linkedin, segmento, cidade_uf, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, decisor, dor_principal, observacoes, canal_principal, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao, valor_potencial, probabilidade, data_proposta, data_fechamento, newsletter_optin) values ('v2#1', true, 'Marcos Oliveira', 'ClinicaSaúde LTDA', 'CEO', 'marcos@clinicasaude.com.br', '+55 11 99999-0001', null, 'Saúde ocupacional', 'São José do Rio Preto/SP', uid_comerc, 'Outbound', 'Outbound manual', 'Morno', 'pipeline', 'Qualificado', true, 'Baixa adoção de sistema', 'Respondeu e topou entender custo do problema.', 'Email + WhatsApp', '2026-04-07', '2026-04-08', 'Enviar Raio-X', '2026-04-09', 15000, 0.25, null, null, false);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, email, whatsapp, linkedin, segmento, cidade_uf, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, decisor, dor_principal, observacoes, canal_principal, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao, valor_potencial, probabilidade, data_proposta, data_fechamento, newsletter_optin) values ('v2#2', true, 'Fernanda Castro', 'FinTech Segura', 'CFO', 'fernanda@fintechsegura.com', '+55 11 99999-0002', null, 'Fintech / Operações', 'São Paulo/SP', uid_comerc, 'Outbound', 'LinkedIn', 'Quente', 'pipeline', 'Raio-X Feito', true, 'Retrabalho operacional', 'Score alto, custo anual relevante.', 'WhatsApp', '2026-04-07', '2026-04-08', 'Agendar revisão', '2026-04-10', 30000, 0.45, null, null, false);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, email, whatsapp, linkedin, segmento, cidade_uf, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, decisor, dor_principal, observacoes, canal_principal, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao, valor_potencial, probabilidade, data_proposta, data_fechamento, newsletter_optin) values ('v2#3', true, 'Rafaela Martins', 'ImobiPrime', 'Sócia', 'rafaela@imobiprime.com', '+55 11 99999-0003', null, 'Imobiliária', 'Ribeirão Preto/SP', uid_comerc, 'Indicação', 'Networking', 'Frio', 'pipeline', 'Prospecção', true, 'Leads no WhatsApp', 'Bom fit, sem urgência clara ainda.', 'Email', '2026-04-08', '2026-04-08', 'Enviar D3', '2026-04-11', 12000, 0.1, null, null, true);

-- ----- 42 leads reais do v1 -----
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Alex Rocha', false, 'Alex Rocha', 'Rocha Prime Imóveis', 'CEO', '55 18 99752-8065', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-06', '2026-04-06', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Rocha & Gomes - Advocacia e Consultoria Jurídica', false, null, 'Rocha & Gomes - Advocacia e Consultoria Jurídica', null, '18 99695.5260', null, 'Outro', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-06', '2026-04-06', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Scatolin Imóveis', false, null, 'Scatolin Imóveis', null, '18 99684-2082', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-06', '2026-04-06', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Guilherme Arantes', false, 'Guilherme Arantes', 'Arantes Imobiliária', 'CEO', '67 99245-2475', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-06', '2026-04-06', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#José Alves', false, 'José Alves', 'Imobiliária JR', 'CEO', '18 3743-4144', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-06', '2026-04-06', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#3L Imóveis', false, null, '3L Imóveis', null, '67 98484-6003', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-06', '2026-04-06', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Gustavo Dourado', false, 'Gustavo Dourado', 'Imobiliaria V8', 'CEO', '(18) 99669-2737', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-07', '2026-04-07', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Daterra Imóveis', false, null, 'Daterra Imóveis', null, '(67) 3509-7474', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-07', '2026-04-07', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Imobiliária Provenzano Imóveis', false, null, 'Imobiliária Provenzano Imóveis', null, '67 992895363', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-07', '2026-04-07', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#MATSUMOTO IMÓVEIS', false, null, 'MATSUMOTO IMÓVEIS', null, '(67) 99979-5062', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-07', '2026-04-07', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Imobiliaria Silvia Imoveis', false, null, 'Imobiliaria Silvia Imoveis', null, '(67) 98128-7002', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-07', '2026-04-07', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Imobiliária Lema', false, null, 'Imobiliária Lema', null, '(18) 99608-4217', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-07', '2026-04-07', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Imobiliária Residence', false, null, 'Imobiliária Residence', null, '(18) 99722-8437', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-07', '2026-04-07', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Imobiliária Imperium', false, null, 'Imobiliária Imperium', null, '(18) 3822-2500', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Nutrição', null, '2026-04-07', '2026-04-07', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Imobiliária Líder', false, null, 'Imobiliária Líder', null, '(18) 3821-6737', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-08', '2026-04-08', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Imobiliária Stella Maris', false, null, 'Imobiliária Stella Maris', null, '(18) 3821-3738', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-08', '2026-04-08', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#José Narciso', false, 'José Narciso', 'Imobiliária José Narciso', 'CEO', '(18) 3821-3914', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Nutrição', null, '2026-04-08', '2026-04-08', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#DISARI IMÓVEIS', false, null, 'DISARI IMÓVEIS', null, '(18) 99618-3003', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-08', '2026-04-08', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Ricardo', false, 'Ricardo', 'Farmacia Satelite', 'CEO', '(18) 99702-3904', null, 'Saúde', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-08', '2026-04-08', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Farmácia Barbosa', false, null, 'Farmácia Barbosa', null, '(18) 3742-5100', null, 'Saúde', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-08', '2026-04-08', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Drogaria Total', false, null, 'Drogaria Total', null, '(18) 3742-2566', null, 'Saúde', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Nutrição', null, '2026-04-08', '2026-04-08', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Ralf', false, 'Ralf', 'Phormula Ativa', 'CEO', '(18) 3742-3495', null, 'Saúde', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-08', '2026-04-08', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Drogaria 7PHARMA', false, null, 'Drogaria 7PHARMA', null, '(67) 3524-0730', null, 'Saúde', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-09', '2026-04-09', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#FARMA 3 LAGOAS', false, null, 'FARMA 3 LAGOAS', null, '(67) 2104-6144', null, 'Saúde', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-09', '2026-04-09', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Farmácia Nossa Senhora Aparecida', false, null, 'Farmácia Nossa Senhora Aparecida', null, '(67) 99141-0170', null, 'Saúde', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Nutrição', null, '2026-04-09', '2026-04-09', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Farmais Dracena', false, null, 'Farmais Dracena', null, '(18) 3821-4349', null, 'Saúde', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-09', '2026-04-09', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Farmacia Santa Lucia', false, null, 'Farmacia Santa Lucia', null, '(18) 3821-5747', null, 'Saúde', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-09', '2026-04-09', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Farmácia Alquimista', false, null, 'Farmácia Alquimista', null, '(18) 3822-4393', null, 'Saúde', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-09', '2026-04-09', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Farmácia Dracena', false, null, 'Farmácia Dracena', null, '(13) 3222-2413', null, 'Saúde', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Nutrição', null, '2026-04-09', '2026-04-09', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Farmácia DROGAZÉ', false, null, 'Farmácia DROGAZÉ', null, '(18) 3821-1164', null, 'Saúde', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Nutrição', null, '2026-04-09', '2026-04-09', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Atlântida Imóveis', false, null, 'Atlântida Imóveis', null, '(18) 3722-1348', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-09', '2026-04-09', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Central Imóveis', false, null, 'Central Imóveis', null, '(18) 3722-1200', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-09', '2026-04-09', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Imobiliária Maercio Imóveis', false, null, 'Imobiliária Maercio Imóveis', null, '(18) 99604-3939', null, 'Imobiliária', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-10', '2026-04-10', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#D.R.E. Engenharia', false, null, 'D.R.E. Engenharia', null, '67981940897', null, 'Outro', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-10', '2026-04-10', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Silva & Barreti Defesa Ambiental e Florestal', false, null, 'Silva & Barreti Defesa Ambiental e Florestal', null, '67981301550', null, 'Outro', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-10', '2026-04-10', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#UNIFARDAS CONFECÇÕES', false, null, 'UNIFARDAS CONFECÇÕES', null, '6735792160', null, 'Outro', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-10', '2026-04-10', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Kelco Petcare', false, null, 'Kelco Petcare', null, '1121126693', null, 'Outro', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-10', '2026-04-10', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Studio Edna Takabayashi', false, null, 'Studio Edna Takabayashi', null, '18997480332', null, 'Outro', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-10', '2026-04-10', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#BRAVA Engenharia e Consultoria', false, null, 'BRAVA Engenharia e Consultoria', null, '(18) 99778-1156', null, 'Outro', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-10', '2026-04-10', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Geometrisa', false, null, 'Geometrisa', null, '(18) 99739-2680', null, 'Outro', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-10', '2026-04-10', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#X5 Engenharia', false, null, 'X5 Engenharia', null, '(18) 99668-9653', null, 'Outro', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-10', '2026-04-10', null, null);
  insert into public.leads (legacy_id, is_demo, nome, empresa, cargo, whatsapp, linkedin, segmento, responsavel_id, motion, fonte, temperatura, funnel_stage, crm_stage, observacoes, data_primeiro_contato, data_ultimo_toque, proxima_acao, data_proxima_acao) values ('v1#Gaia Engenharia & Projetos', false, null, 'Gaia Engenharia & Projetos', null, '(17) 99745-7729', null, 'Outro', uid_comerc, 'Outbound', 'Lista fria', 'Frio', 'arquivado', 'Perdido', null, '2026-04-10', '2026-04-10', null, null);

-- ----- Raio-X (3 demos) -----
  insert into public.raio_x (lead_id, responsavel_id, data_oferta, preco_lista, voucher_desconto, gratuito, pago, data_pagamento, score, perda_anual_estimada, nivel, saida_recomendada, call_revisao, data_call, observacoes) select id, uid_comerc, '2026-04-08', 97, 0, false, true, '2026-04-08', 78, 142000, 'Alto', 'Qualificado para revisão', true, '2026-04-10', 'Score alto e perda anual clara.' from public.leads where nome = 'Fernanda Castro' and is_demo = true limit 1;
  insert into public.raio_x (lead_id, responsavel_id, data_oferta, preco_lista, voucher_desconto, gratuito, pago, data_pagamento, score, perda_anual_estimada, nivel, saida_recomendada, call_revisao, data_call, observacoes) select id, uid_comerc, '2026-04-09', 97, 50, false, false, null, 55, 96000, 'Médio', 'Nutrição / Newsletter', false, null, 'Voucher usado para destravar.' from public.leads where nome = 'Marcos Oliveira' and is_demo = true limit 1;

-- ----- Cadência (3 demos, D0-D30) -----
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D0',  'Email + WhatsApp', 'Contexto / dor',                           '2026-04-08', 'pendente' from public.leads where nome = 'Marcos Oliveira' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D3',  'Email + WhatsApp', 'Impacto / custo invisível',                '2026-04-11', 'pendente' from public.leads where nome = 'Marcos Oliveira' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D7',  'Email + WhatsApp', 'Autoridade / qualificação',                '2026-04-15', 'pendente' from public.leads where nome = 'Marcos Oliveira' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D11', 'Email + WhatsApp', 'Convite certo (Raio-X, call, diagnóstico)','2026-04-19', 'pendente' from public.leads where nome = 'Marcos Oliveira' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D16', 'Email + WhatsApp', 'Porta aberta + newsletter',                '2026-04-24', 'pendente' from public.leads where nome = 'Marcos Oliveira' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D30', 'Email + WhatsApp', 'Retomada suave',                           '2026-05-08', 'pendente' from public.leads where nome = 'Marcos Oliveira' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D0',  'WhatsApp',         'Contexto / dor',                           '2026-04-08', 'pendente' from public.leads where nome = 'Fernanda Castro' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D3',  'WhatsApp',         'Impacto / custo invisível',                '2026-04-11', 'pendente' from public.leads where nome = 'Fernanda Castro' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D7',  'WhatsApp',         'Autoridade / qualificação',                '2026-04-15', 'pendente' from public.leads where nome = 'Fernanda Castro' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D11', 'WhatsApp',         'Convite certo (Raio-X, call, diagnóstico)','2026-04-19', 'pendente' from public.leads where nome = 'Fernanda Castro' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D16', 'WhatsApp',         'Porta aberta + newsletter',                '2026-04-24', 'pendente' from public.leads where nome = 'Fernanda Castro' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D30', 'WhatsApp',         'Retomada suave',                           '2026-05-08', 'pendente' from public.leads where nome = 'Fernanda Castro' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D0',  'Email',            'Contexto / dor',                           '2026-04-08', 'pendente' from public.leads where nome = 'Rafaela Martins' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D3',  'Email',            'Impacto / custo invisível',                '2026-04-11', 'pendente' from public.leads where nome = 'Rafaela Martins' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D7',  'Email',            'Autoridade / qualificação',                '2026-04-15', 'pendente' from public.leads where nome = 'Rafaela Martins' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D11', 'Email',            'Convite certo (Raio-X, call, diagnóstico)','2026-04-19', 'pendente' from public.leads where nome = 'Rafaela Martins' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D16', 'Email',            'Porta aberta + newsletter',                '2026-04-24', 'pendente' from public.leads where nome = 'Rafaela Martins' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;
  insert into public.cadencia (lead_id, passo, canal, objetivo, data_prevista, status) select id, 'D30', 'Email',            'Retomada suave',                           '2026-05-08', 'pendente' from public.leads where nome = 'Rafaela Martins' and is_demo = true limit 1 on conflict (lead_id, passo) do nothing;

-- ----- Newsletter -----
  insert into public.newsletter (lead_id, responsavel_id, optin, data_entrada, ultima_edicao_enviada, proxima_edicao_sugerida, status, cta_provavel, observacoes) select id, uid_comerc, true, '2026-04-08', null, '2026-04-22', 'Ativo', 'Responder newsletter', 'Sem timing agora, mas fit bom.' from public.leads where nome = 'Rafaela Martins' and is_demo = true limit 1;

-- ----- Metas semanais (13 semanas) -----
  insert into public.meta_semanal (inicio, fim, meta_leads, meta_resp, meta_raiox, meta_calls, meta_props, meta_fech) values ('2026-04-06','2026-04-12',15,4,2,2,1,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_semanal (inicio, fim, meta_leads, meta_resp, meta_raiox, meta_calls, meta_props, meta_fech) values ('2026-04-13','2026-04-19',15,4,2,2,1,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_semanal (inicio, fim, meta_leads, meta_resp, meta_raiox, meta_calls, meta_props, meta_fech) values ('2026-04-20','2026-04-26',15,4,2,2,1,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_semanal (inicio, fim, meta_leads, meta_resp, meta_raiox, meta_calls, meta_props, meta_fech) values ('2026-04-27','2026-05-03',15,4,2,2,1,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_semanal (inicio, fim, meta_leads, meta_resp, meta_raiox, meta_calls, meta_props, meta_fech) values ('2026-05-04','2026-05-10',15,4,2,2,1,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_semanal (inicio, fim, meta_leads, meta_resp, meta_raiox, meta_calls, meta_props, meta_fech) values ('2026-05-11','2026-05-17',15,4,2,2,1,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_semanal (inicio, fim, meta_leads, meta_resp, meta_raiox, meta_calls, meta_props, meta_fech) values ('2026-05-18','2026-05-24',15,4,2,2,1,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_semanal (inicio, fim, meta_leads, meta_resp, meta_raiox, meta_calls, meta_props, meta_fech) values ('2026-05-25','2026-05-31',15,4,2,2,1,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_semanal (inicio, fim, meta_leads, meta_resp, meta_raiox, meta_calls, meta_props, meta_fech) values ('2026-06-01','2026-06-07',15,4,2,2,1,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_semanal (inicio, fim, meta_leads, meta_resp, meta_raiox, meta_calls, meta_props, meta_fech) values ('2026-06-08','2026-06-14',15,4,2,2,1,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_semanal (inicio, fim, meta_leads, meta_resp, meta_raiox, meta_calls, meta_props, meta_fech) values ('2026-06-15','2026-06-21',15,4,2,2,1,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_semanal (inicio, fim, meta_leads, meta_resp, meta_raiox, meta_calls, meta_props, meta_fech) values ('2026-06-22','2026-06-28',15,4,2,2,1,1) on conflict (organizacao_id, inicio) do nothing;

-- ----- Metas mensais (9 meses) -----
  insert into public.meta_mensal (rotulo, inicio, fim, meta_leads, meta_raiox, meta_calls, meta_props, meta_fech) values ('Apr/2026', '2026-04-01','2026-04-30', 60,8,6,3,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_mensal (rotulo, inicio, fim, meta_leads, meta_raiox, meta_calls, meta_props, meta_fech) values ('May/2026', '2026-05-01','2026-05-31', 60,8,6,3,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_mensal (rotulo, inicio, fim, meta_leads, meta_raiox, meta_calls, meta_props, meta_fech) values ('Jun/2026', '2026-06-01','2026-06-30', 60,8,6,3,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_mensal (rotulo, inicio, fim, meta_leads, meta_raiox, meta_calls, meta_props, meta_fech) values ('Jul/2026', '2026-07-01','2026-07-31', 60,8,6,3,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_mensal (rotulo, inicio, fim, meta_leads, meta_raiox, meta_calls, meta_props, meta_fech) values ('Aug/2026', '2026-08-01','2026-08-31', 60,8,6,3,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_mensal (rotulo, inicio, fim, meta_leads, meta_raiox, meta_calls, meta_props, meta_fech) values ('Sep/2026', '2026-09-01','2026-09-30', 60,8,6,3,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_mensal (rotulo, inicio, fim, meta_leads, meta_raiox, meta_calls, meta_props, meta_fech) values ('Oct/2026', '2026-10-01','2026-10-31', 60,8,6,3,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_mensal (rotulo, inicio, fim, meta_leads, meta_raiox, meta_calls, meta_props, meta_fech) values ('Nov/2026', '2026-11-01','2026-11-30', 60,8,6,3,1) on conflict (organizacao_id, inicio) do nothing;
  insert into public.meta_mensal (rotulo, inicio, fim, meta_leads, meta_raiox, meta_calls, meta_props, meta_fech) values ('Dec/2026', '2026-12-01','2026-12-31', 60,8,6,3,1) on conflict (organizacao_id, inicio) do nothing;

end $$;

-- ==========================================================
-- Passo 3: remove os defaults temporários
-- ==========================================================
alter table public.leads        alter column organizacao_id drop default;
alter table public.raio_x       alter column organizacao_id drop default;
alter table public.cadencia     alter column organizacao_id drop default;
alter table public.newsletter   alter column organizacao_id drop default;
alter table public.ligacoes     alter column organizacao_id drop default;
alter table public.meta_semanal alter column organizacao_id drop default;
alter table public.meta_mensal  alter column organizacao_id drop default;
alter table public.lead_evento  alter column organizacao_id drop default;

-- ==========================================================
-- Total: 1 org (Guilds), 4 membros, 3 leads-demo + 42 leads reais
-- ==========================================================
