-- Adiciona colunas de score ao v_leads_enriched (no fim, pra não quebrar ordem)
create or replace view public.v_leads_enriched as
 select l.id,
    l.organizacao_id,
    l.legacy_id,
    l.is_demo,
    l.nome,
    l.empresa,
    l.cargo,
    l.email,
    l.whatsapp,
    l.linkedin,
    l.instagram,
    l.segmento,
    l.cidade_uf,
    l.site,
    l.responsavel_id,
    l.motion,
    l.fonte,
    l.temperatura,
    l.prioridade,
    l.funnel_stage,
    l.crm_stage,
    l.decisor,
    l.fit_icp,
    l.dor_principal,
    l.observacoes,
    l.canal_principal,
    l.data_entrada,
    l.data_primeiro_contato,
    l.data_ultimo_toque,
    l.data_proxima_acao,
    l.proxima_acao,
    l.valor_potencial,
    l.probabilidade,
    l.receita_ponderada,
    l.data_proposta,
    l.data_fechamento,
    l.newsletter_optin,
    l.created_at,
    l.updated_at,
    l.motivo_perda,
    l.motivo_perda_detalhe,
    l.percepcao_vendedor,
    l.valor_setup,
    l.valor_mensal,
    l.link_proposta,
    CURRENT_DATE - l.data_ultimo_toque AS dias_sem_tocar,
    NULL::text AS semana_proxima_acao,
    'sem_acao'::text AS urgencia,
    p.display_name AS responsavel_nome,
    p.email AS responsavel_email,
    r.status_oferta AS raiox_status,
    r.nivel AS raiox_nivel,
    r.score AS raiox_score,
    r.data_pagamento AS raiox_data_pagamento,
    ( SELECT count(*) AS count
           FROM ligacoes
          WHERE ligacoes.lead_id = l.id) AS total_ligacoes,
    -- Score multi-dimensional (no fim pra não quebrar a ordem existente)
    l.score_icp_fit,
    l.score_engajamento,
    l.score_comportamento,
    l.score_total,
    l.score_calculado_em,
    l.custom_fields
   FROM leads l
     LEFT JOIN profiles p ON p.id = l.responsavel_id
     LEFT JOIN raio_x r ON r.lead_id = l.id;

grant select on public.v_leads_enriched to authenticated;
